/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'match': MotiaStream<{ type: string; startTime?: number; winner?: string; error?: string; msg?: string }>
  }

  interface Handlers {
    'MatchExpiryJob': CronHandler<never>
    'MatchAPI': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'player.joined'; data: never } | { topic: 'run.code'; data: never }>
    'GameEngine': EventHandler<never, never>
    'CodeRunner': EventHandler<never, { topic: 'code.processed'; data: never }>
  }
    
}